// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/michalq/go-bootstrap-project/internal/api-v1"
	"github.com/michalq/go-bootstrap-project/internal/api-v1/controller"
	"github.com/michalq/go-bootstrap-project/internal/api-v1/formatter"
	"github.com/michalq/go-bootstrap-project/internal/dal/user"
	user2 "github.com/michalq/go-bootstrap-project/internal/modules/user"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeApi(mongoDB *mongo.Database) (*apiv1.V1Routing, error) {
	users := user.NewUsers(mongoDB)
	userFormatter := formatter.NewUserFormatter()
	verifier := user2.NewVerifier(users)
	contextScoperUserController := controller.NewContextScopedUserController(users, userFormatter, verifier)
	v1Routing := apiv1.NewV1Routing(contextScoperUserController)
	return v1Routing, nil
}
